### ISSUE TITLE
check/enforce file permissions

### ISSUE THREAD

**Issue by winstan** [ubc-cpsc/handback#2]
File permissions are critical - set them wrong and you make more information available than you want to.
This script should check (and enforce?) permissions - Everything in the directory should have no permissions for group or other except for the directory itself (750) and .htaccess (640). The group should be 'ta' for both folder and file.

**Comment by joelpittet** [comment]
Ideally, you'd keep the sensitive file out of the document root so even if the file was set with the incorrect permissions it wouldn't be exposed, but still available to the script.  This may be the case already... just adding my 2¢
